/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    portfolio: Portfolio;
    experience: Experience;
    visitors: Visitor;
    keywords: Keyword;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    visitors: VisitorsSelect<false> | VisitorsSelect<true>;
    keywords: KeywordsSelect<false> | KeywordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'visitor-content': VisitorContent;
    landing: Landing;
    labels: Label;
  };
  globalsSelect: {
    'visitor-content': VisitorContentSelect<false> | VisitorContentSelect<true>;
    landing: LandingSelect<false> | LandingSelect<true>;
    labels: LabelsSelect<false> | LabelsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Human-friendly name for this asset (shown in the media picker).
   */
  title: string;
  /**
   * Alternative text for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  title: string;
  /**
   * Short feature name shown above the title and in nav/related cards.
   */
  eyebrow: string;
  /**
   * URL slug for /portfolio/[slug]. Auto-filled from the title if left blank; editable.
   */
  slug?: string | null;
  /**
   * Sort order (ascending). Lower shows first; /portfolio redirects to the lowest.
   */
  order?: number | null;
  /**
   * Square/circular thumbnail for nav + landing cards.
   */
  thumbnail?: (number | null) | Media;
  summary?: string | null;
  overview?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * System Design diagram (authored in features/portfolio/graph/diagrams).
   */
  diagramKey: 'context-aware-routes';
  /**
   * Subtitle under "Key Decisions". Defaults to the eyebrow when blank.
   */
  keyDecisionsTitle?: string | null;
  keyDecisions?:
    | {
        title: string;
        description?: string | null;
        conclusion: 'up' | 'down';
        points?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  relatedContent?:
    | (
        | {
            relationTo: 'portfolio';
            value: number | Portfolio;
          }
        | {
            relationTo: 'experience';
            value: number | Experience;
          }
      )[]
    | null;
  scope?: (number | Keyword)[] | null;
  craft?: (number | Keyword)[] | null;
  /**
   * Hidden terms that surface this item in search but never render on the page.
   */
  searchKeywords?: (number | Keyword)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  role: string;
  company: string;
  /**
   * URL anchor for /experience#slug. Auto-filled from the role if left blank; editable.
   */
  slug?: string | null;
  startDate: string;
  endDate?: string | null;
  current?: boolean | null;
  /**
   * Optional company logo.
   */
  companyLogo?: (number | null) | Media;
  showcase?:
    | {
        image: number | Media;
        /**
         * Optional "Visit site" link for this showcase image.
         */
        url?: string | null;
        /**
         * Optional caption / accessible label for this image.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  responsibilities?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  scope?: (number | Keyword)[] | null;
  craft?: (number | Keyword)[] | null;
  deepDive?:
    | {
        title?: string | null;
        description?: string | null;
        details?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hidden terms that surface this item in search but never render on the page.
   */
  searchKeywords?: (number | Keyword)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords".
 */
export interface Keyword {
  id: number;
  /**
   * Immutable machine key (seeder/exporter upsert identity). Auto-filled from the label if left blank; set once, cannot be edited after.
   */
  key: string;
  label: string;
  /**
   * Scope = areas/domains (Frontend, Platform). Craft = skills & how (React, Testing). Search-only = hidden recruiter term, feeds search only, never rendered.
   */
  category: 'scope' | 'craft' | 'searchOnly';
  aliases?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors".
 */
export interface Visitor {
  id: number;
  company: string;
  role: string;
  /**
   * URL slug for /dear/[company]. Auto-filled from the company if left blank; editable.
   */
  slug: string;
  /**
   * Company avatar for the welcome banner + card.
   */
  companyLogo?: (number | null) | Media;
  /**
   * Link to the job post the expectations were sourced from.
   */
  jobPostUrl: string;
  expectations: {
    expectation: string;
    reply: string;
    relevantContent?:
      | (
          | {
              relationTo: 'portfolio';
              value: number | Portfolio;
            }
          | {
              relationTo: 'experience';
              value: number | Experience;
            }
        )[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'visitors';
        value: number | Visitor;
      } | null)
    | ({
        relationTo: 'keywords';
        value: number | Keyword;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  eyebrow?: T;
  slug?: T;
  order?: T;
  thumbnail?: T;
  summary?: T;
  overview?:
    | T
    | {
        text?: T;
        id?: T;
      };
  diagramKey?: T;
  keyDecisionsTitle?: T;
  keyDecisions?:
    | T
    | {
        title?: T;
        description?: T;
        conclusion?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  relatedContent?: T;
  scope?: T;
  craft?: T;
  searchKeywords?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  role?: T;
  company?: T;
  slug?: T;
  startDate?: T;
  endDate?: T;
  current?: T;
  companyLogo?: T;
  showcase?:
    | T
    | {
        image?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  responsibilities?:
    | T
    | {
        text?: T;
        id?: T;
      };
  scope?: T;
  craft?: T;
  deepDive?:
    | T
    | {
        title?: T;
        description?: T;
        details?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  searchKeywords?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors_select".
 */
export interface VisitorsSelect<T extends boolean = true> {
  company?: T;
  role?: T;
  slug?: T;
  companyLogo?: T;
  jobPostUrl?: T;
  expectations?:
    | T
    | {
        expectation?: T;
        reply?: T;
        relevantContent?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords_select".
 */
export interface KeywordsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  category?: T;
  aliases?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitor-content".
 */
export interface VisitorContent {
  id: number;
  welcomeGreeting?: string | null;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Phrase in the intro to highlight (e.g. "Relevant content"). Optional.
   */
  highlightPhrase?: string | null;
  constants?: {
    expectations?: string | null;
    reply?: string | null;
    relevantContent?: string | null;
    jobPost?: string | null;
    dearCompanyNav?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number;
  sections?:
    | {
        /**
         * Which band this is. Binds to its renderer; the copy comes from the matching group below.
         */
        key: 'tldr' | 'experience' | 'portfolio' | 'moreAboutMe' | 'contact';
        /**
         * Nav text. The band’s anchor id + search title derive from this (slugified).
         */
        navLabel: string;
        /**
         * Hidden terms that surface this section in search but never render.
         */
        searchKeywords?: (number | Keyword)[] | null;
        id?: string | null;
      }[]
    | null;
  hero?: {
    title?: string | null;
    driveLabel?: string | null;
    drive?: string | null;
    listLabel?: string | null;
    /**
     * Craft keywords shown in the hero (before scope), in attach order.
     */
    craft?: (number | Keyword)[] | null;
    /**
     * Scope keywords shown in the hero (after craft), in attach order.
     */
    scope?: (number | Keyword)[] | null;
  };
  tldr?: {
    greeting?: string | null;
    subtitle?: string | null;
    blocks?:
      | {
          title: string;
          body?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  experience?: {
    heading?: string | null;
    subheader?: string | null;
    diveInto?: {
      subheader?: string | null;
      items?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    ctaLabel?: string | null;
  };
  portfolio?: {
    heading?: string | null;
    subheader?: string | null;
    diveInto?: {
      subheader?: string | null;
      items?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    ctaLabel?: string | null;
  };
  moreAboutMe?: {
    heading?: string | null;
    subheader?: string | null;
    teaser?: {
      eyebrow?: string | null;
      title?: string | null;
      description?: string | null;
      items?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Button text. The button only renders when a portfolio write-up is attached below.
       */
      ctaLabel?: string | null;
      /**
       * Portfolio write-up this section links to. Attach one to show the button; empty hides it.
       */
      ctaPortfolioItem?: (number | null) | Portfolio;
    };
  };
  contact?: {
    header?: string | null;
    subheader?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels".
 */
export interface Label {
  id: number;
  constants?: {
    portfolio?: {
      overview?: string | null;
      systemDesign?: string | null;
      keyDecisions?: string | null;
      conclusion?: string | null;
      relevantContent?: string | null;
    };
    experience?: {
      roleDescription?: string | null;
      scope?: string | null;
      craft?: string | null;
      deepDive?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitor-content_select".
 */
export interface VisitorContentSelect<T extends boolean = true> {
  welcomeGreeting?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  highlightPhrase?: T;
  constants?:
    | T
    | {
        expectations?: T;
        reply?: T;
        relevantContent?: T;
        jobPost?: T;
        dearCompanyNav?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        key?: T;
        navLabel?: T;
        searchKeywords?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        driveLabel?: T;
        drive?: T;
        listLabel?: T;
        craft?: T;
        scope?: T;
      };
  tldr?:
    | T
    | {
        greeting?: T;
        subtitle?: T;
        blocks?:
          | T
          | {
              title?: T;
              body?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  experience?:
    | T
    | {
        heading?: T;
        subheader?: T;
        diveInto?:
          | T
          | {
              subheader?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
        ctaLabel?: T;
      };
  portfolio?:
    | T
    | {
        heading?: T;
        subheader?: T;
        diveInto?:
          | T
          | {
              subheader?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
        ctaLabel?: T;
      };
  moreAboutMe?:
    | T
    | {
        heading?: T;
        subheader?: T;
        teaser?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaPortfolioItem?: T;
            };
      };
  contact?:
    | T
    | {
        header?: T;
        subheader?: T;
        description?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels_select".
 */
export interface LabelsSelect<T extends boolean = true> {
  constants?:
    | T
    | {
        portfolio?:
          | T
          | {
              overview?: T;
              systemDesign?: T;
              keyDecisions?: T;
              conclusion?: T;
              relevantContent?: T;
            };
        experience?:
          | T
          | {
              roleDescription?: T;
              scope?: T;
              craft?: T;
              deepDive?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}