// ⚠️  GENERATED by scripts/generate-tokens.mts from app/globals.css — DO NOT EDIT.
// Author tokens in app/globals.css; run `pnpm generate:tokens` to refresh
// (it also runs on `predev` and the pre-commit hook).

import type { DSThemeColorGroup } from './tokens'

/** Colour foundations scraped from the `:root` `@ds` tags. */
export const generatedColorGroups: DSThemeColorGroup[] = [
  {
    id: 'roles',
    title: 'Color roles · semantic',
    caption: 'provenance',
    tokens: [
      {
        name: 'background',
        cssVar: '--background',
        swatch: 'bg-background',
      },
      {
        name: 'foreground',
        cssVar: '--foreground',
        swatch: 'bg-foreground',
        dark: true,
      },
      {
        name: 'card',
        cssVar: '--card',
        swatch: 'bg-card',
      },
      {
        name: 'card-foreground',
        cssVar: '--card-foreground',
        swatch: 'bg-card-foreground',
        dark: true,
      },
      {
        name: 'muted',
        cssVar: '--muted',
        swatch: 'bg-muted',
      },
      {
        name: 'muted-foreground',
        cssVar: '--muted-foreground',
        swatch: 'bg-muted-foreground',
        dark: true,
      },
      {
        name: 'border',
        cssVar: '--border',
        swatch: 'bg-border',
      },
      {
        name: 'input',
        cssVar: '--input',
        swatch: 'bg-input',
      },
      {
        name: 'primary',
        cssVar: '--primary',
        swatch: 'bg-primary',
        dark: true,
      },
      {
        name: 'primary-foreground',
        cssVar: '--primary-foreground',
        swatch: 'bg-primary-foreground',
      },
      {
        name: 'label',
        cssVar: '--label',
        swatch: 'bg-label',
        dark: true,
      },
      {
        name: 'accent',
        cssVar: '--accent',
        swatch: 'bg-accent',
        dark: true,
      },
      {
        name: 'accent-foreground',
        cssVar: '--accent-foreground',
        swatch: 'bg-accent-foreground',
      },
      {
        name: 'ring',
        cssVar: '--ring',
        swatch: 'bg-ring',
        dark: true,
      },
    ],
  },
  {
    id: 'states',
    title: 'Interaction states',
    caption: 'provenance',
    tokens: [
      {
        name: 'feedback',
        cssVar: '--feedback',
        swatch: 'bg-feedback',
        dark: true,
      },
      {
        name: 'selection',
        cssVar: '--selection',
        swatch: 'bg-selection',
        dark: true,
      },
      {
        name: 'overlay',
        cssVar: '--overlay',
        swatch: 'bg-overlay',
      },
    ],
  },
]

/** Every `@utility text-*` role, in declaration order. */
export const dsThemeTextStyles: string[] = [
  'text-header',
  'text-subtitle',
  'text-subheader',
  'text-lead',
  'text-body',
  'text-list',
  'text-eyebrow',
  'text-hero-headline',
  'text-hero-list',
  'text-aside',
  'text-nav',
  'text-ui',
  'text-ui-bold',
  'text-card-title',
  'text-card-body',
  'text-meta',
  'text-meta-bold',
]
