/**
 * Generates `lib/design-system/tokens.generated.ts` from `app/globals.css`.
 *
 * `globals.css` is the single source of truth for the design tokens. This script
 * scrapes it so the TS side (the /design-system viewer + `cn()`'s twMerge config)
 * never restates a token name by hand — you author a token once, in CSS, and the
 * generated catalog follows. The generated file is a build artifact: DO NOT EDIT it.
 *
 * What it reads from globals.css:
 *  - Colour groups — a `@ds-groups` header declares the foundations (id, title,
 *    caption mode), and each `:root` token tagged `/* @ds <group> [dark] *​/`
 *    is bucketed into its group, in declaration order.
 *  - Text styles — every `@utility text-*` block, in declaration order.
 *
 * The palette foundation (raw stock Tailwind stops) is NOT generated — those stops
 * aren't declared in globals.css to scrape — it stays hand-curated in tokens.ts.
 *
 * Run with: `pnpm generate:tokens` (also runs on `predev` + the pre-commit hook).
 */
import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

import prettier from 'prettier'

const CSS_PATH = path.resolve(process.cwd(), 'app/globals.css')
const OUT_PATH = path.resolve(process.cwd(), 'lib/design-system/tokens.generated.ts')

type Group = { id: string; title: string; caption: 'provenance' | 'value' }
type Token = { name: string; cssVar: string; swatch: string; dark?: boolean }

/** Parse the `@ds-groups id="Title"/caption …` header into ordered group defs. */
function parseGroups(css: string): Group[] {
  const header = css.match(/@ds-groups\s+([^*]+?)\s*\*\//)
  if (!header) return []
  const groups: Group[] = []
  const re = /(\w+)="([^"]+)"\/(\w+)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(header[1]))) {
    groups.push({ id: m[1], title: m[2], caption: m[3] as Group['caption'] })
  }
  return groups
}

/** Bucket every tagged `:root` token (`--x: …; /* @ds <group> [dark] *​/`) by group. */
function parseColorTokens(css: string): Record<string, Token[]> {
  const root = css.match(/:root\s*\{([\s\S]*?)\n\}/)
  const body = root ? root[1] : ''
  const byGroup: Record<string, Token[]> = {}
  const re = /--([\w-]+):\s*[^;]+;\s*\/\*\s*@ds\s+([\w-]+)([^*]*)\*\//g
  let m: RegExpExecArray | null
  while ((m = re.exec(body))) {
    const [, name, group, rest] = m
    const token: Token = { name, cssVar: `--${name}`, swatch: `bg-${name}` }
    if (/\bdark\b/.test(rest)) token.dark = true
    ;(byGroup[group] ??= []).push(token)
  }
  return byGroup
}

/** Every `@utility text-*` name, in declaration order. */
function parseTextStyles(css: string): string[] {
  const names: string[] = []
  const re = /@utility\s+(text-[\w-]+)\s*\{/g
  let m: RegExpExecArray | null
  while ((m = re.exec(css))) names.push(m[1])
  return names
}

export async function generateTokens(): Promise<void> {
  const css = fs.readFileSync(CSS_PATH, 'utf8')

  const groupDefs = parseGroups(css)
  const byGroup = parseColorTokens(css)
  const generatedColorGroups = groupDefs.map((g) => ({
    id: g.id,
    title: g.title,
    caption: g.caption,
    tokens: byGroup[g.id] ?? [],
  }))
  const dsThemeTextStyles = parseTextStyles(css)

  const raw = `// ⚠️  GENERATED by scripts/generate-tokens.mts from app/globals.css — DO NOT EDIT.
// Author tokens in app/globals.css; run \`pnpm generate:tokens\` to refresh
// (it also runs on \`predev\` and the pre-commit hook).

import type { DSThemeColorGroup } from './tokens'

/** Colour foundations scraped from the \`:root\` \`@ds\` tags. */
export const generatedColorGroups: DSThemeColorGroup[] = ${JSON.stringify(
    generatedColorGroups,
    null,
    2,
  )}

/** Every \`@utility text-*\` role, in declaration order. */
export const dsThemeTextStyles: string[] = ${JSON.stringify(dsThemeTextStyles, null, 2)}
`

  const cfg = await prettier.resolveConfig(OUT_PATH)
  const formatted = await prettier.format(raw, { ...cfg, parser: 'typescript', filepath: OUT_PATH })
  fs.writeFileSync(OUT_PATH, formatted)
}

// Run when invoked directly (`pnpm generate:tokens`), but not when imported by the watcher.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await generateTokens()
  console.log('✓ Tokens written to lib/design-system/tokens.generated.ts')
}
